from antithesis.assertions import reachable
from antithesis.random import get_random

from bank.helper import (
    MAX_INITIAL_ACCOUNTS,
    MIN_INITIAL_ACCOUNTS,
    TOTAL_BALANCE,
    distribute_balance,
    random_padding,
)
from test_client.database import Database


def setup(db: Database) -> None:
    with db.connect() as connection:
        with connection.transaction():
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS accounts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    balance BIGINT NOT NULL,
                    padding TEXT NULL
                )
                """
            )
            connection.execute(
                "ALTER TABLE accounts ADD COLUMN IF NOT EXISTS padding TEXT NULL"
            )
            connection.execute("LOCK TABLE accounts IN EXCLUSIVE MODE")
            count = connection.execute("SELECT COUNT(*) FROM accounts").fetchone()[0]
            if count:
                return

            account_count = get_random() % (
                MAX_INITIAL_ACCOUNTS - MIN_INITIAL_ACCOUNTS + 1
            ) + MIN_INITIAL_ACCOUNTS
            balances = distribute_balance(TOTAL_BALANCE, account_count)
            with connection.cursor() as cursor:
                cursor.executemany(
                    "INSERT INTO accounts (balance, padding) VALUES (%s, %s)",
                    [(balance, random_padding()) for balance in balances],
                )

    reachable(
        "Bank: initial accounts created",
        {"accounts": account_count, "total_balance": TOTAL_BALANCE},
    )
