services:
  postgres_under_test:
    init: true
    container_name: postgres_under_test
    hostname: postgres_under_test
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  antigres:
    init: true
    container_name: antigres
    hostname: antigres
    restart: always
    image: antigres:latest
    volumes:
      - ./observations:/opt/antithesis/observations
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_under_test:5432/postgres
      - RUST_BACKTRACE=1
      - SELECTED_TESTS=uuids,cksum,bank_test
      - ANTIGRES_KEEP_LOGGING_ON=0

  egglog:
    init: true
    container_name: egglog
    hostname: egglog
    restart: always
    image: antigres:latest
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres_under_test:5432/postgres
      - RUST_BACKTRACE=1
      - SELECTED_TESTS=egglog
      - ANTIGRES_KEEP_LOGGING_ON=0
